name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "JDomergue91"
          git config user.email "JDomergue91@users.noreply.github.com"
      
      - name: Push to GitHub Pages
        run: |
          git remote add origin https://github.com/JDomergue91/github-actions.git
          git push origin main
