name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Déclencher le workflow sur la branche main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build  # Remplace cette commande par celle nécessaire pour générer ton site

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public  # Remplace ce chemin par le dossier où se trouve ton site généré
