name: Workflow avec Jobs Dépendants

on:
  push:
    branches:
      - main

jobs:
    
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build project
        run: echo "Compiling the project..."

  test:
    runs-on: ubuntu-latest
    needs: build  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run tests
        run: echo "Running tests..."
