name: Utiliser des Secrets GitHub

on:
  push:
    branches:
      - main

jobs:
  use-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Lire le secret API_KEY
        run: |
          echo "La clé API est : ${{ secrets.API_KEY }}"

      - name: Afficher le secret de manière masquée
        run: |
          echo "La clé API masquée : ***"
